### ISSUE TITLE
$axios is undefined in async asyncData method in production (nuxt build && nuxt start)

### ISSUE THREAD

**Issue by acrolink** [nuxt-community/axios-module#281]
The following code works perfect in development (`nuxt` script):

```
  async asyncData({ $axios, params }) {
    let response = await $axios.get(`/api/items`)
    return { entities: response.data.data }
  }
```

However, in production (`nuxt build && nuxt start`) I get this error:

```
 ERROR  Cannot read property 'get' of undefined                            18:31:39

  at asyncData (03b2f45fe1a8907386a4.js:1:0)
  at C (server.js:1:0)
  at Promise.all.h.map.n (server.js:1:0)
  at Array.map (<anonymous>)
  at e.default (server.js:1:0)
```

**Comment by acrolink** [comment]
The issue was caused because I used a custom `nuxt.config.js` for production with the name `nuxt.config.prod.js`.

On build I was not using the `-c nuxt.config.prod.js` switch.
This switch must be declared on both tasks `nuxt build` and `nuxt start`

Works as expected.
