### ISSUE TITLE
LaravelJWT error with ExpiredAuthSessionError: Both token and refresh token have expired. Your request was aborted.

### ISSUE THREAD

**Issue by oommgg** [nuxt-community/axios-module#459]
"@nuxtjs/auth-next": "5.0.0-1608280312.c5867c3"
"nuxt": "^2.14.12",

```js
  auth: {
    strategies: {
      laravelJWT: {
        provider: 'laravel/jwt',
        url: '/api/auth',
        endpoints: {
          login: { url: '/api/auth/login', method: 'post' },
          refresh: { url: '/api/auth/refresh', method: 'post' },
          user: { url: '/api/auth/user', method: 'get' },
          logout: { url: '/api/auth/logout', method: 'post' },
        },
        token: {
          property: 'token',
          maxAge: 60 * 60,
        },
        refreshToken: {
          property: 'token',
          maxAge: 20160 * 60,
        },
        user: {
          property: 'user',
        },
      },
    },
  },
  axios: {
    proxy: true,
    credentials: true,
  },
  proxy: {
    '/api': {
      target: process.env.API_URL || process.env.APP_URL,
    },
  },
  router: {
    middleware: ['auth'],
  },
```

1. When logged in, then do "logout", and refresh page got:

    ExpiredAuthSessionError: Both token and refresh token have expired. Your request was aborted.
    at eval (webpack-internal:///./node_modules/@nuxtjs/auth-next/dist/runtime.mjs:798:17)

2. clean all cookie from chrome, refresh page got same problem

    ExpiredAuthSessionError: Both token and refresh token have expired. Your request was aborted.
    at eval (webpack-internal:///./node_modules/@nuxtjs/auth-next/dist/runtime.mjs:798:17)

**Comment by oommgg** [comment]
downgrade to @nuxtjs/auth-next@5.0.0-1607693598.34d83ea working fine
