### ISSUE TITLE
Request failed with status code 404 with nuxtServerInit

### ISSUE THREAD

**Issue by PrajapatiDhara1510** [nuxt-community/axios-module#541]
I have been trying to solve this issue from last 2-3 days.

Here is my nuxt.config.js

```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'
export default {
  ssr:true,
  dev: true,
  server: {
    port: 3000, // default: 3000
    host: '10.***.**.**'
  },
  head: {
    title: 'nuxt-sample',
    htmlAttrs: {
      lang: 'en'
    },
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' },
      { name: 'format-detection', content: 'telephone=no' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  plugins: [
    {src: '~/plugins/axios.js', mode: 'client'}
  ],
  components: true,
  buildModules: [
    '@nuxtjs/eslint-module'
  ],

  modules: [
    'bootstrap-vue/nuxt',
    '@nuxtjs/axios'
  ],

  axios: {
    baseURL: 'http://www.myproject.com/api/',
  },

  build: {
    friendlyErrors: false
  }
}
```
plugins/axios.js

```
export default function ({ $axios, redirect }) {
  $axios.onRequest((config) => {
    config.headers.common['Domain-name'] = window.location.hostname
  })

  $axios.onError((error) => {
    const code = parseInt(error.response && error.response.status)
    if (code === 301) {
      // return redirect('https://www.google.com/')
    }
  })
}
```

Now when I run the same URL on a pages/index.vue, as seen below it called successfully and getting the response. 

```
<template>
  <Tutorial />
</template>

<script>
export default {
  created () {
    this.getContents()
  },
  methods: {
    async getContents () {
      await this.$store.dispatch('getConfigurations', { domain: 'myproject.com' }).then((res) => {
        if (res.status) {
          console.log(res)
        }
      })
    }
  }
}
</script>
```

but when I tried to call on `nuxtServerInit` method it is not working. Here is my method in actions/index.js

```
export const state = () => ({})
export const getters = {}
export const mutations = {}

export const actions = {
  async nuxtServerInit ({ dispatch }) {
    console.log('called nuxtServerInit')
    try {
      await dispatch('getConfigurations', { domain: 'myproject.com' })
      //const res = await this.$axios.post('vendors/oauth/domain/configuration', { domain: 'myproject.com' })
      //console.log('response', res)
    } catch (err) {
      console.error(err)
    }
  },
  getConfigurations ({ commit }, data) {
    return this.$axios({
      method: 'post',
      url: 'vendors/oauth/domain/configuration',
      data: { domain: data.domain }
    })
      .then(function (response) {
        console.log('called this')
        console.log(response)
        return response
      })
      .catch(function (error) {
        console.log(error)
        if (
          {}.hasOwnProperty.call(error, 'response') &&
            error.response !== undefined
        ) {
          if (
            {}.hasOwnProperty.call(error.response, 'data') &&
              error.response.data !== undefined
          ) {
            return error.response.data
          } else {
            throw error
          }
        } else {
          throw error
        }
      })
  }
}
```
So when I hot reload the site I get the following error

> Request failed with status code 404                                                                                                          10:35:18
> 
>   at createError (node_modules/axios/lib/core/createError.js:16:15)
>   at settle (node_modules/axios/lib/core/settle.js:17:12)
>   at Unzip.handleStreamEnd (node_modules/axios/lib/adapters/http.js:269:11)
>   at Unzip.emit (events.js:326:22)
>   at endReadableNT (_stream_readable.js:1241:12)
>   at processTicksAndRejections (internal/process/task_queues.js:84:21)

I can't get what is wrong here. API is working in pages but not with nuxtServerInit. I am assuming if it works normally then it should work with the `nuxtServerInit`. I am new with all this so cannot figure out the issue. Please help me

**Comment by Murtdha** [comment]
did you find the solution ??
