### ISSUE TITLE
Cannot restart nuxt:  Cannot read properties of undefined (reading 'options')   

### ISSUE THREAD

**Issue by ErikasMasaitis** [nuxt-community/axios-module#603]
after adding axios module to my `nuxt.config.js` i am getting this error:

```
 ERROR  Cannot restart nuxt:  Cannot read properties of undefined (reading 'options')                                                             6:58:14 PM

  at axiosModule (node_modules/@nuxtjs/axios/lib/module.js:12:13)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:450:101)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:2682:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:183:9)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:96:10)
```

```
export default {
    css: ['~/assets/css/main.css'],
    postcss: {
        plugins: {
            tailwindcss: {},
            autoprefixer: {},
        },
    },
    modules: ['@nuxtjs/axios'],

    axios: {
        baseURL: 'http://127.0.0.1:8000/',
        prefix: '/api',
    },
}
```

nuxt version: 3.4.3
axios version: 5.13.6

**Comment by danielroe** [comment]
This module is not compatible with Nuxt v3, though of course you can directly use axios in Nuxt 3 if you don't like the built-in `$fetch`...
