### ISSUE TITLE
error during build: substr of undefined

### ISSUE THREAD

**Issue by uptownhr** [nuxt-community/axios-module#61]
This error currently occurs when building nuxt.

```
> nuxt build

2017-11-15T22:30:12.263Z nuxt:build Building...
TypeError: Cannot read property 'substr' of undefined
    at ModuleContainer.nuxtAxios (/www/node_modules/@nuxtjs/axios/lib/index.js:38:47)
    at /www/node_modules/nuxt/lib/core/module.js:133:29
    at new Promise (<anonymous>)
    at ModuleContainer._callee2$ (/www/node_modules/nuxt/lib/core/module.js:132:12)
    at tryCatch (/www/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/www/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/www/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/www/node_modules/nuxt/dist/nuxt.js:954:30)
    at /www/node_modules/nuxt/dist/nuxt.js:965:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:655:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
2017-11-15T22:30:12.558Z nuxt:build App root: /www

```

**Comment by uptownhr** [comment]
this is my yarnlock for the axios module

```
"@nuxtjs/axios@^4.0.0":
  version "4.0.0"
  resolved "https://registry.yarnpkg.com/@nuxtjs/axios/-/axios-4.0.0.tgz#8d99d253671aa5a2042dcfada7f2f1343594c5ad"
  dependencies:
    axios "^0.16.2"
    chalk "^2.1.0"
    debug "^3.0.1"
    nuxt "^1.0.0-rc8"
    whatwg-url "^6.1.0"
```

**Comment by pi0** [comment]
Options, (especially those about baseURL) should be handled much better with `5.x`. Please see the new docs.

Sorry for answering late.
